### ISSUE TITLE
Question about cupy

### ISSUE THREAD

**Issue by MEYE66** [sczhou/IGNN#7]
Thank you for the nice work! I can install pyinn&cupy,matmul successfuly,but error when run runner.py.
Some of my configure:
CUDA version:  nvcc -V 
_nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
Python 3.7, PyTorch 1.1.0

Traceback (most recent call last):
  File "runner.py", line 15, in <module>
    from core.build import bulid_net
  File "/home/lixiaohan/workspace/IGNN/core/build.py", line 16, in <module>
    from models.IGNN import IGNN
  File "/home/lixiaohan/workspace/IGNN/models/IGNN.py", line 6, in <module>
    from models.submodules import *
  File "/home/lixiaohan/workspace/IGNN/models/submodules.py", line 9, in <module>
    from models.graph_agg import *
  File "/home/lixiaohan/workspace/IGNN/models/graph_agg.py", line 13, in <module>
    from models.lib import ops
  File "/home/lixiaohan/workspace/IGNN/models/lib/ops.py", line 10, in <module>
    import pyinn
  File "/home/lixiaohan/.conda/envs/ignn/lib/python3.7/site-packages/pyinn/__init__.py", line 1, in <module>
    from .ncrelu import ncrelu
  File "/home/lixiaohan/.conda/envs/ignn/lib/python3.7/site-packages/pyinn/ncrelu.py", line 2, in <module>
    from pyinn.utils import Stream, Dtype, load_kernel
  File "/home/lixiaohan/.conda/envs/ignn/lib/python3.7/site-packages/pyinn/utils.py", line 18, in <module>
    @cupy.util.memoize(for_each_device=True)
AttributeError: module 'cupy' has no attribute 'util'

**Comment by sczhou** [comment]
Hi, please ensure your CuPy version is below 8.0 since the 'util' attribute is removed after version CuPy 8.0. You can try to use CuPy 7.3.0 instead.

**Comment by MEYE66** [comment]
Thank your suggestions, but  I have meet another problem. （Wish you a Happy New Year in advance ！）

Traceback (most recent call last):
  File "runner.py", line 15, in <module>
    from core.build import bulid_net
  File "/home/lixiaohan/workspace/IGNN/core/build.py", line 16, in <module>
    from models.IGNN import IGNN
  File "/home/lixiaohan/workspace/IGNN/models/IGNN.py", line 6, in <module>
    from models.submodules import *
  File "/home/lixiaohan/workspace/IGNN/models/submodules.py", line 9, in <module>
    from models.graph_agg import *
  File "/home/lixiaohan/workspace/IGNN/models/graph_agg.py", line 13, in <module>
    from models.lib import ops
  File "/home/lixiaohan/workspace/IGNN/models/lib/ops.py", line 17, in <module>
    import matmul_cuda
ImportError: /home/lixiaohan/.local/lib/python3.7/site-packages/matmul-0.0.0-py3.7-linux-x86_64.egg/matmul_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __cudaRegisterFatBinaryEnd

**Comment by sczhou** [comment]
If you install matmul_cuda successfully, please check the compatibility of your Pytorch and Cuda version. The Cuda version is suggested to be 9.0. (Thanks, Happy New Year!)

**Comment by RachelHui12** [comment]
> Thank your suggestions, but I have meet another problem. （Wish you a Happy New Year in advance ！）
> 
> Traceback (most recent call last):
> File "runner.py", line 15, in
> from core.build import bulid_net
> File "/home/lixiaohan/workspace/IGNN/core/build.py", line 16, in
> from models.IGNN import IGNN
> File "/home/lixiaohan/workspace/IGNN/models/IGNN.py", line 6, in
> from models.submodules import *
> File "/home/lixiaohan/workspace/IGNN/models/submodules.py", line 9, in
> from models.graph_agg import *
> File "/home/lixiaohan/workspace/IGNN/models/graph_agg.py", line 13, in
> from models.lib import ops
> File "/home/lixiaohan/workspace/IGNN/models/lib/ops.py", line 17, in
> import matmul_cuda
> ImportError: /home/lixiaohan/.local/lib/python3.7/site-packages/matmul-0.0.0-py3.7-linux-x86_64.egg/matmul_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __cudaRegisterFatBinaryEnd

I also meet this problem, did you solve it?
